#!/usr/bin/env python3
"""
scripts/report_server.py
------------------------
Mini Flask app that serves a markdown-rendered report of the product catalogue.

Flask 2.2.5    — CVE-2023-30861 (session cookie exposure)  Fix: >= 2.3.2
mistune 0.8.4  — CVE-2022-34749 (ReDoS via nested lists)   Fix: >= 2.0.3
"""

from flask import Flask, jsonify, render_template_string   # CVE-2023-30861
import mistune                                              # CVE-2022-34749
import requests

app = Flask(__name__)
app.secret_key = "dev-only-not-secret"  # intentionally weak for demo

MARKDOWN_TEMPLATE = """
<!DOCTYPE html>
<html>
<head><title>Product Report</title>
<style>body{font-family:sans-serif;max-width:800px;margin:40px auto;}</style>
</head>
<body>{{ content|safe }}</body>
</html>
"""

DEMO_MARKDOWN = """
# Product Catalogue Report

## Summary

This report is generated by `report_server.py` using **mistune 0.8.4** and
**Flask 2.2.5**, both of which contain known CVEs.

## Vulnerable Components (Python)

| Package    | Version | CVE              | Severity |
|------------|---------|------------------|----------|
| Flask      | 2.2.5   | CVE-2023-30861   | HIGH     |
| mistune    | 0.8.4   | CVE-2022-34749   | MEDIUM   |
| requests   | 2.28.2  | CVE-2023-32681   | HIGH     |
| PyJWT      | 2.3.0   | CVE-2022-29217   | HIGH     |
| urllib3    | 1.26.14 | CVE-2023-43804   | MEDIUM   |
| aiohttp    | 3.8.1   | CVE-2023-37276   | HIGH     |
| ipython    | 7.29.0  | CVE-2022-21699   | HIGH     |
| numpy      | 1.21.0  | CVE-2021-41496   | MEDIUM   |
| setuptools | 65.3.0  | CVE-2022-40897   | HIGH     |
| certifi    | 2022.9.24|CVE-2022-23491   | MEDIUM   |

## Fix

Upgrade all packages to the fixed versions listed in `docs/CVE-REPORT.md`.
No application code changes are required.
"""


@app.route("/")
def index():
    # mistune 0.8.4: parsing deeply nested lists causes catastrophic backtracking
    html_content = mistune.markdown(DEMO_MARKDOWN)
    return render_template_string(MARKDOWN_TEMPLATE, content=html_content)


@app.route("/api/status")
def status():
    return jsonify({"status": "running", "note": "vulnerable demo — do not use in production"})


if __name__ == "__main__":
    print("Starting report server on http://localhost:5000")
    app.run(debug=True, port=5000)
